package main

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Leaderboard) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "members":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Members")
				return
			}
			if z.Members == nil {
				z.Members = make(map[string]*Member, zb0002)
			} else if len(z.Members) > 0 {
				for key := range z.Members {
					delete(z.Members, key)
				}
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				var za0002 *Member
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Members")
					return
				}
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Members", za0001)
						return
					}
					za0002 = nil
				} else {
					if za0002 == nil {
						za0002 = new(Member)
					}
					err = za0002.DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Members", za0001)
						return
					}
				}
				z.Members[za0001] = za0002
			}
		case "members_index":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "MembersIndex")
				return
			}
			if cap(z.MembersIndex) >= int(zb0003) {
				z.MembersIndex = (z.MembersIndex)[:zb0003]
			} else {
				z.MembersIndex = make([]*MemberIndex, zb0003)
			}
			for za0003 := range z.MembersIndex {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "MembersIndex", za0003)
						return
					}
					z.MembersIndex[za0003] = nil
				} else {
					if z.MembersIndex[za0003] == nil {
						z.MembersIndex[za0003] = new(MemberIndex)
					}
					err = z.MembersIndex[za0003].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "MembersIndex", za0003)
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Leaderboard) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "name"
	err = en.Append(0x83, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "members"
	err = en.Append(0xa7, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Members)))
	if err != nil {
		err = msgp.WrapError(err, "Members")
		return
	}
	for za0001, za0002 := range z.Members {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Members")
			return
		}
		if za0002 == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = za0002.EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Members", za0001)
				return
			}
		}
	}
	// write "members_index"
	err = en.Append(0xad, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.MembersIndex)))
	if err != nil {
		err = msgp.WrapError(err, "MembersIndex")
		return
	}
	for za0003 := range z.MembersIndex {
		if z.MembersIndex[za0003] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.MembersIndex[za0003].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "MembersIndex", za0003)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Leaderboard) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "name"
	o = append(o, 0x83, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "members"
	o = append(o, 0xa7, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Members)))
	for za0001, za0002 := range z.Members {
		o = msgp.AppendString(o, za0001)
		if za0002 == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = za0002.MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Members", za0001)
				return
			}
		}
	}
	// string "members_index"
	o = append(o, 0xad, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78)
	o = msgp.AppendArrayHeader(o, uint32(len(z.MembersIndex)))
	for za0003 := range z.MembersIndex {
		if z.MembersIndex[za0003] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.MembersIndex[za0003].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "MembersIndex", za0003)
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Leaderboard) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "members":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Members")
				return
			}
			if z.Members == nil {
				z.Members = make(map[string]*Member, zb0002)
			} else if len(z.Members) > 0 {
				for key := range z.Members {
					delete(z.Members, key)
				}
			}
			for zb0002 > 0 {
				var za0001 string
				var za0002 *Member
				zb0002--
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Members")
					return
				}
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					za0002 = nil
				} else {
					if za0002 == nil {
						za0002 = new(Member)
					}
					bts, err = za0002.UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Members", za0001)
						return
					}
				}
				z.Members[za0001] = za0002
			}
		case "members_index":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MembersIndex")
				return
			}
			if cap(z.MembersIndex) >= int(zb0003) {
				z.MembersIndex = (z.MembersIndex)[:zb0003]
			} else {
				z.MembersIndex = make([]*MemberIndex, zb0003)
			}
			for za0003 := range z.MembersIndex {
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					z.MembersIndex[za0003] = nil
				} else {
					if z.MembersIndex[za0003] == nil {
						z.MembersIndex[za0003] = new(MemberIndex)
					}
					bts, err = z.MembersIndex[za0003].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "MembersIndex", za0003)
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Leaderboard) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 8 + msgp.MapHeaderSize
	if z.Members != nil {
		for za0001, za0002 := range z.Members {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001)
			if za0002 == nil {
				s += msgp.NilSize
			} else {
				s += za0002.Msgsize()
			}
		}
	}
	s += 14 + msgp.ArrayHeaderSize
	for za0003 := range z.MembersIndex {
		if z.MembersIndex[za0003] == nil {
			s += msgp.NilSize
		} else {
			s += z.MembersIndex[za0003].Msgsize()
		}
	}
	return
}
